{% set version = "12.0.0" %}

package:
  name: mermaid-cli
  version: {{ version }}

source:
  url: https://registry.npmjs.org/@mermaid-js/mermaid-cli/-/mermaid-cli-{{ version }}.tgz
  sha256: b5b43bc60c2e6bc87f7d12ab3e6e78883c799213ea5b015363fecdd5e6363c84

build:
  number: 0

requirements:
  build:
    - nodejs
    - pnpm
  host:
    - nodejs
    - pnpm
    - pnpm-licenses >=2.1.0
  run:
    - nodejs

test:
  commands:
    - mmdc --version
    - mmdc --help

about:
  home: https://github.com/mermaid-js/mermaid-cli
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: 'Command-line interface for Mermaid'

extra:
  recipe-maintainers:
    - ajaypnair09
